### ISSUE TITLE
2_extract_files.py (IndexError: list index out of range)

### ISSUE THREAD

**Issue by sanolans** [sujiongming/UCF-101_video_classification#14]
When running the 2_extract_file,  I get the following error:
`Traceback (most recent call last):
  File "2_extract_files.py", line 99, in <module>
    main()
  File "2_extract_files.py", line 96, in main
    extract_files()
  File "2_extract_files.py", line 38, in extract_files
    video_parts = get_video_parts(video_path)
  File "2_extract_files.py", line 76, in get_video_parts
    filename = parts[3]
IndexError: list index out of range`
Can anyone please guide me ?

**Comment by sanolans** [comment]
I see my mistake now, my video path had 2 paths instead of three.
