### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by sanolans** [sujiongming/UCF-101_video_classification#15]
I get the following error when I run the CNN_train_UCF101.py file.
`Traceback (most recent call last):
  File "CNN_train_UCF101.py", line 18, in <module>
    data = DataSet()
  File "D:\Clones\UCF-101_video_classification-master\UCFdata.py", line 32, in __init__
    self.classes = self.get_classes()
  File "D:\Clones\UCF-101_video_classification-master\UCFdata.py", line 64, in get_classes
    if item[1] not in classes:
IndexError: list index out of range`

When I do `print (self.data)` I get something like this:  `['train', 'HeadMassage', 'v_HeadMassage_g12_c05', '169'], []` for each image in the dataset.

can anyone please tell me what I'm doing wrong.
Window 10
Python 3.7.6

**Comment by sanolans** [comment]
issue resoled, closing now.
